language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install coveralls

# commands to run tests
script:
  - python -m setup check -r -s
  - flake8
  - pep257
  - nosetests

# upload coverage data to coveralls.io
after_success:
  - coveralls
