language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install coveralls

# commands to run tests
script:
  - flake8
  - pep257
  - nosetests

# upload coverage data to coveralls.io
after_success:
  - coveralls
